pipeline {
  options {
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    IMAGE_NAME = 'static-ws'
    IMAGE_REL = v1r0
    CONTAINER_NAME = 'container-static-ws'
    TEST_LOCAL_PORT = 8081
    DEPLOY_PROD = false
    PARAMETERS_FILE = "${JENKINS_HOME}/parameters.groovy"
  }
  
  triggers {
    cron('H */4 * * 1-5')
  }

  agent { node { label 'master' } }
  
  stages {
    stage('Step 1') {
      echo "Step 1"
      git branch: "master",
        credentialsId: 'GithubSshCredentials',
        url: 'https://github.com/yourAccount/cicd-static-website.git'
    }
    stage('Step 2') {
      sh "docker build -t ${IMAGE_NAME}:${IMAGE_REL} -f ../Dockerfile"
      sh "[ -z \"\$(docker ps -a | grep ${CONTAINER_NAME} 2>/dev/null)\" ] || docker rm -f container-static-ws"
      sh "docker run --detach --name ${CONTAINER_NAME} --rm --publish ${TEST_LOCAL_PORT}:80 ${IMAGE_NAME}:${IMAGE_REL}"
    }
  }
}
